### ISSUE TITLE
Symbol's function definition is void: flycheck-checker-option-vars

### ISSUE THREAD

**Issue by andschwa** [purcell/flycheck-ledger#5]
Hey @purcell!

With Flycheck version: 0.24snapshot (package: 20150707.9) (from Melpa), `flycheck-ledger` now throws an error on load:

`Symbol's function definition is void: flycheck-checker-option-vars`

Are you still maintaining this, or is there a better way to use Flycheck with Ledger files?

Thanks,

Andy

**Comment by purcell** [comment]
I came across this today: what has happened is that macros in `flycheck` have changed incompatibly, so `flycheck-ledger` simply needs to be recompiled using the new `flycheck` macro definitions, and then it works fine. Just reinstall the package and all should be well.

**Comment by andschwa** [comment]
Wow. How did I not try that... Sorry for wasting your time! Thanks :)

**Comment by purcell** [comment]
No problem at all. Happy if you're finding this code useful. :-)
