### ISSUE TITLE
Errors when used with an encrypted ledger

### ISSUE THREAD

**Issue by FrancisMurillo** [purcell/flycheck-ledger#6]
When using this with an encrypted gpg ledger, it fails to check the balance correctly. By the way, good tool.

**Comment by purcell** [comment]
Thanks. Hmm, this is a tricky one -- there's an easy fix using a different `flycheck` option, but then the result will be that `flycheck` will temporarily write an unencrypted copy of the contents to disk, with no _absolute_ guarantee that it will later be removed. I think that may be worse than this not working. What do you think?

**Comment by FrancisMurillo** [comment]
I had the same thoughts about it. I can live without the checking if data is compromised but what a darn waste. 

Apparently, this was an issue [checking encrypted files](https://github.com/flycheck/flycheck/issues/222) and going to the manual it states that [encrypted files are not recommended](http://www.flycheck.org/en/latest/user/syntax-checks.html?highlight=encrypt). So... I guess this might not be your issue.

So... nuts.
